### ISSUE TITLE
Subscription not working in flutter

### ISSUE THREAD

**Issue by MrFarhan** [mhd999/appsync-subscription#1]
Got below error while using your code with my subscription.

`flutter: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("subscription")`

**Comment by mhd999** [comment]
Can you share your integration code?

**Comment by MrFarhan** [comment]
@mhd999 I have used the exact same code you mentioned in the readme

**Comment by MrFarhan** [comment]
Below is the code screenshot, I think we need to wrap this in Future builder or Stream to get the subscription data but I couldn't find any of them in your code, Pls correct me if I am wrong or made any mistake in the code :

![fluttercode](https://user-images.githubusercontent.com/26528236/200289282-d24c2a54-a9e8-4ff2-ac3c-bdd8c97e91e5.png)

**Comment by mhd999** [comment]
Can you share the result of 
```
curl --location --request POST 'https://XXXXXX.appsync-api.{REGION}.amazonaws.com/graphql' \
--header 'x-api-key: {API_KEY}' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"subscription {\n        onCreateOrder {\n          OrdersId\n        }\n}","variables":{}}'

```

**Comment by MrFarhan** [comment]
> Got below error while using your code with my subscription.
> 
> `flutter: NoSuchMethodError: The method '[]' was called on null. Receiver: null Tried calling: []("subscription")`

I had to decline the project due to this issue, how ever the error while calling subscription is mentioned in my initial message

**Comment by mhd999** [comment]
Hi,

the curl I shared in the previous comment should return a response similar to this:


```
    "extensions": {
        "subscription": {
            "mqttConnections":   [...],
             "newSubscriptions" : { ... }
            }
       }     
```

I don't think your AWS AppSync returns this response hence why the library can't parse the response to find the subscription topic. 

If you are not able to share that response with me I can't debug the issue.

**Comment by Samuel-ML** [comment]
Hello, I'm facing this error

{
  "errors" : [ {
    "errorType" : "BadRequestException",
    "message" : "Subscriptions over MQTT is not supported."
  } ]
}
